"""Release calendar from sig-release READMEs. Generated calendar.yaml is committed and human-verified."""
from __future__ import annotations
from datetime import date, datetime
from pathlib import Path
import re
import yaml
from core.model import Milestone

PREFIX = "k8s:"
_DATE = re.compile(r"(?:Mon|Tues|Wednes|Thurs|Fri|Satur|Sun)day\s+(\d{1,2})(?:st|nd|rd|th)\s+([A-Z][a-z]+)\s+(\d{4})")
_KEYS = [  # (key, line must match this regex, case-insensitive)
    ("start", r"start of release cycle"),
    ("enhancements_freeze", r"enhancements freeze"),
    ("code_freeze", r"code freeze"),
    ("release", r"\bv?1\.\d+\.0 released"),
]
_EXCLUDE = re.compile(r"coming|alpha|beta|rc\.", re.I)


def _first_date(line: str) -> date | None:
    m = _DATE.search(line)
    if not m:
        return None
    day, month, year = m.groups()
    return datetime.strptime(f"{day} {month} {year}", "%d %B %Y").date()


def parse_timeline(readme: str) -> dict[str, date]:
    out: dict[str, date] = {}
    for line in readme.splitlines():
        for key, pat in _KEYS:
            if key in out or not re.search(pat, line, re.I):
                continue
            if key in ("enhancements_freeze", "code_freeze") and _EXCLUDE.search(line):
                continue  # "Code Freeze is Coming", alpha/beta/rc rows
            if key == "release" and re.search(r"alpha|beta|rc\.", line, re.I):
                continue
            d = _first_date(line)
            if d:
                out[key] = d
    return out


def build_milestones(sig_release_repo: Path, max_minor: int = 60) -> list[Milestone]:
    scheduled: dict[int, dict[str, date]] = {}
    for readme in sorted((sig_release_repo / "releases").glob("release-1.*/README.md")):
        minor = int(readme.parent.name.split(".")[1])
        d = parse_timeline(readme.read_text())
        if "code_freeze" in d and "release" in d:
            scheduled[minor] = d
    out = []
    for minor in range(0, max_minor + 1):
        d = scheduled.get(minor, {})
        out.append(Milestone(f"{PREFIX}v1.{minor}", minor, d.get("code_freeze"), d.get("release"), dict(d)))
    return out


def write_calendar(milestones: list[Milestone], path: Path) -> None:
    rows = [{"id": m.id, "ordinal": m.ordinal, "dates": {k: v.isoformat() for k, v in sorted(m.dates.items())}} for m in milestones]
    path.write_text("# Generated by adapters/k8s/milestones.py from sig-release READMEs. Verify by hand; edit if wrong.\n"
                    + yaml.safe_dump(rows, sort_keys=False))


def load_calendar(path: Path) -> list[Milestone]:
    rows = yaml.safe_load(path.read_text()) or []
    out = []
    for r in rows:
        dates = {k: date.fromisoformat(v) for k, v in (r.get("dates") or {}).items()}
        out.append(Milestone(r["id"], int(r["ordinal"]), dates.get("code_freeze"), dates.get("release"), dates))
    return out
